### ISSUE TITLE
CB-38376 : Raw Sensor (Ingress) Events Not Forwarded

### ISSUE THREAD

**Issue by jjfallete** [carbonblack/cb-event-forwarder#223]
I'm documenting this as an issue here to help track resolution. I compared 3.7.5 and 3.8.1 and would guess this is an issue within the protobuf_message_processor ... I wasn't able to immediately identify the issue though.

Ref Support Case: 00254589

**Comment by jjfallete** [comment]
@[jeromekleinen-kbc](https://github.com/jeromekleinen-kbc) I've opened a new issue on this, I see you were the first to report this publicly, but the issue was closed due to confusion.

**Comment by jerome-kleinen-kbc-be** [comment]
@jjfallete do the release notes of https://github.com/carbonblack/cb-event-forwarder/releases/tag/v3.8.4 imply that this issue is resolved?

**Comment by jjfallete** [comment]
@jerome-kleinen-kbc-be good question. I'll ask CB Support in my support case and report back. I do not believe so, but let me know if you find out otherwise first. Edit for clarity: I do not work for CB.

**Comment by jjfallete** [comment]
@jerome-kleinen-kbc-be -- CB Support confirmed 3.8.4 has still not addressed this issue and has advised we continue on the 3.7.x branch.
